/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ats.courses.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Courses service. Represents a row in the &quot;ATS_Courses&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ats.courses.model.impl.CoursesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ats.courses.model.impl.CoursesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Courses
 * @generated
 */
@ProviderType
public interface CoursesModel
	extends BaseModel<Courses>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a courses model instance should use the {@link Courses} interface instead.
	 */

	/**
	 * Returns the primary key of this courses.
	 *
	 * @return the primary key of this courses
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this courses.
	 *
	 * @param primaryKey the primary key of this courses
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this courses.
	 *
	 * @return the uuid of this courses
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this courses.
	 *
	 * @param uuid the uuid of this courses
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the courses ID of this courses.
	 *
	 * @return the courses ID of this courses
	 */
	public long getCoursesId();

	/**
	 * Sets the courses ID of this courses.
	 *
	 * @param coursesId the courses ID of this courses
	 */
	public void setCoursesId(long coursesId);

	/**
	 * Returns the group ID of this courses.
	 *
	 * @return the group ID of this courses
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this courses.
	 *
	 * @param groupId the group ID of this courses
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this courses.
	 *
	 * @return the company ID of this courses
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this courses.
	 *
	 * @param companyId the company ID of this courses
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this courses.
	 *
	 * @return the user ID of this courses
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this courses.
	 *
	 * @param userId the user ID of this courses
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this courses.
	 *
	 * @return the user uuid of this courses
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this courses.
	 *
	 * @param userUuid the user uuid of this courses
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this courses.
	 *
	 * @return the user name of this courses
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this courses.
	 *
	 * @param userName the user name of this courses
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this courses.
	 *
	 * @return the create date of this courses
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this courses.
	 *
	 * @param createDate the create date of this courses
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this courses.
	 *
	 * @return the modified date of this courses
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this courses.
	 *
	 * @param modifiedDate the modified date of this courses
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the courses_img of this courses.
	 *
	 * @return the courses_img of this courses
	 */
	@AutoEscape
	public String getCourses_img();

	/**
	 * Sets the courses_img of this courses.
	 *
	 * @param Courses_img the courses_img of this courses
	 */
	public void setCourses_img(String Courses_img);

	/**
	 * Returns the courses_name of this courses.
	 *
	 * @return the courses_name of this courses
	 */
	@AutoEscape
	public String getCourses_name();

	/**
	 * Sets the courses_name of this courses.
	 *
	 * @param Courses_name the courses_name of this courses
	 */
	public void setCourses_name(String Courses_name);

	/**
	 * Returns the courses_des of this courses.
	 *
	 * @return the courses_des of this courses
	 */
	@AutoEscape
	public String getCourses_des();

	/**
	 * Sets the courses_des of this courses.
	 *
	 * @param Courses_des the courses_des of this courses
	 */
	public void setCourses_des(String Courses_des);

	/**
	 * Returns the courses_type of this courses.
	 *
	 * @return the courses_type of this courses
	 */
	@AutoEscape
	public String getCourses_type();

	/**
	 * Sets the courses_type of this courses.
	 *
	 * @param Courses_type the courses_type of this courses
	 */
	public void setCourses_type(String Courses_type);

	/**
	 * Returns the courses_rating of this courses.
	 *
	 * @return the courses_rating of this courses
	 */
	@AutoEscape
	public String getCourses_rating();

	/**
	 * Sets the courses_rating of this courses.
	 *
	 * @param Courses_rating the courses_rating of this courses
	 */
	public void setCourses_rating(String Courses_rating);

	@Override
	public Courses cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}