/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ats.courses.model.impl;

import com.ats.courses.model.Courses;
import com.ats.courses.service.CoursesLocalServiceUtil;

/**
 * The extended model base implementation for the Courses service. Represents a row in the &quot;ATS_Courses&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CoursesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CoursesImpl
 * @see Courses
 * @generated
 */
public abstract class CoursesBaseImpl
	extends CoursesModelImpl implements Courses {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a courses model instance should use the <code>Courses</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CoursesLocalServiceUtil.addCourses(this);
		}
		else {
			CoursesLocalServiceUtil.updateCourses(this);
		}
	}

}