/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ats.courses.model.impl;

import com.ats.courses.model.Courses;
import com.ats.courses.model.CoursesModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Courses service. Represents a row in the &quot;ATS_Courses&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CoursesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CoursesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CoursesImpl
 * @generated
 */
@JSON(strict = true)
public class CoursesModelImpl
	extends BaseModelImpl<Courses> implements CoursesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a courses model instance should use the <code>Courses</code> interface instead.
	 */
	public static final String TABLE_NAME = "ATS_Courses";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"coursesId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"Courses_img", Types.VARCHAR}, {"Courses_name", Types.VARCHAR},
		{"Courses_des", Types.VARCHAR}, {"Courses_type", Types.VARCHAR},
		{"Courses_rating", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("coursesId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Courses_img", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Courses_name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Courses_des", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Courses_type", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Courses_rating", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ATS_Courses (uuid_ VARCHAR(75) null,coursesId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,Courses_img TEXT null,Courses_name VARCHAR(75) null,Courses_des VARCHAR(75) null,Courses_type VARCHAR(75) null,Courses_rating VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ATS_Courses";

	public static final String ORDER_BY_JPQL =
		" ORDER BY courses.Courses_name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ATS_Courses.Courses_name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COURSES_NAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COURSES_TYPE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CoursesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _coursesId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCoursesId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _coursesId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Courses.class;
	}

	@Override
	public String getModelClassName() {
		return Courses.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Courses, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Courses, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Courses, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Courses)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Courses, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Courses, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Courses)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Courses, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Courses, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Courses, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Courses, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Courses, Object>>();

			attributeGetterFunctions.put("uuid", Courses::getUuid);
			attributeGetterFunctions.put("coursesId", Courses::getCoursesId);
			attributeGetterFunctions.put("groupId", Courses::getGroupId);
			attributeGetterFunctions.put("companyId", Courses::getCompanyId);
			attributeGetterFunctions.put("userId", Courses::getUserId);
			attributeGetterFunctions.put("userName", Courses::getUserName);
			attributeGetterFunctions.put("createDate", Courses::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Courses::getModifiedDate);
			attributeGetterFunctions.put(
				"Courses_img", Courses::getCourses_img);
			attributeGetterFunctions.put(
				"Courses_name", Courses::getCourses_name);
			attributeGetterFunctions.put(
				"Courses_des", Courses::getCourses_des);
			attributeGetterFunctions.put(
				"Courses_type", Courses::getCourses_type);
			attributeGetterFunctions.put(
				"Courses_rating", Courses::getCourses_rating);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Courses, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Courses, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Courses, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Courses, String>)Courses::setUuid);
			attributeSetterBiConsumers.put(
				"coursesId", (BiConsumer<Courses, Long>)Courses::setCoursesId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Courses, Long>)Courses::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Courses, Long>)Courses::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Courses, Long>)Courses::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Courses, String>)Courses::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Courses, Date>)Courses::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Courses, Date>)Courses::setModifiedDate);
			attributeSetterBiConsumers.put(
				"Courses_img",
				(BiConsumer<Courses, String>)Courses::setCourses_img);
			attributeSetterBiConsumers.put(
				"Courses_name",
				(BiConsumer<Courses, String>)Courses::setCourses_name);
			attributeSetterBiConsumers.put(
				"Courses_des",
				(BiConsumer<Courses, String>)Courses::setCourses_des);
			attributeSetterBiConsumers.put(
				"Courses_type",
				(BiConsumer<Courses, String>)Courses::setCourses_type);
			attributeSetterBiConsumers.put(
				"Courses_rating",
				(BiConsumer<Courses, String>)Courses::setCourses_rating);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCoursesId() {
		return _coursesId;
	}

	@Override
	public void setCoursesId(long coursesId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_coursesId = coursesId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getCourses_img() {
		if (_Courses_img == null) {
			return "";
		}
		else {
			return _Courses_img;
		}
	}

	@Override
	public void setCourses_img(String Courses_img) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Courses_img = Courses_img;
	}

	@JSON
	@Override
	public String getCourses_name() {
		if (_Courses_name == null) {
			return "";
		}
		else {
			return _Courses_name;
		}
	}

	@Override
	public void setCourses_name(String Courses_name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Courses_name = Courses_name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCourses_name() {
		return getColumnOriginalValue("Courses_name");
	}

	@JSON
	@Override
	public String getCourses_des() {
		if (_Courses_des == null) {
			return "";
		}
		else {
			return _Courses_des;
		}
	}

	@Override
	public void setCourses_des(String Courses_des) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Courses_des = Courses_des;
	}

	@JSON
	@Override
	public String getCourses_type() {
		if (_Courses_type == null) {
			return "";
		}
		else {
			return _Courses_type;
		}
	}

	@Override
	public void setCourses_type(String Courses_type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Courses_type = Courses_type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCourses_type() {
		return getColumnOriginalValue("Courses_type");
	}

	@JSON
	@Override
	public String getCourses_rating() {
		if (_Courses_rating == null) {
			return "";
		}
		else {
			return _Courses_rating;
		}
	}

	@Override
	public void setCourses_rating(String Courses_rating) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Courses_rating = Courses_rating;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Courses.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Courses.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Courses toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Courses>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CoursesImpl coursesImpl = new CoursesImpl();

		coursesImpl.setUuid(getUuid());
		coursesImpl.setCoursesId(getCoursesId());
		coursesImpl.setGroupId(getGroupId());
		coursesImpl.setCompanyId(getCompanyId());
		coursesImpl.setUserId(getUserId());
		coursesImpl.setUserName(getUserName());
		coursesImpl.setCreateDate(getCreateDate());
		coursesImpl.setModifiedDate(getModifiedDate());
		coursesImpl.setCourses_img(getCourses_img());
		coursesImpl.setCourses_name(getCourses_name());
		coursesImpl.setCourses_des(getCourses_des());
		coursesImpl.setCourses_type(getCourses_type());
		coursesImpl.setCourses_rating(getCourses_rating());

		coursesImpl.resetOriginalValues();

		return coursesImpl;
	}

	@Override
	public Courses cloneWithOriginalValues() {
		CoursesImpl coursesImpl = new CoursesImpl();

		coursesImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		coursesImpl.setCoursesId(
			this.<Long>getColumnOriginalValue("coursesId"));
		coursesImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		coursesImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		coursesImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		coursesImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		coursesImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		coursesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		coursesImpl.setCourses_img(
			this.<String>getColumnOriginalValue("Courses_img"));
		coursesImpl.setCourses_name(
			this.<String>getColumnOriginalValue("Courses_name"));
		coursesImpl.setCourses_des(
			this.<String>getColumnOriginalValue("Courses_des"));
		coursesImpl.setCourses_type(
			this.<String>getColumnOriginalValue("Courses_type"));
		coursesImpl.setCourses_rating(
			this.<String>getColumnOriginalValue("Courses_rating"));

		return coursesImpl;
	}

	@Override
	public int compareTo(Courses courses) {
		int value = 0;

		value = getCourses_name().compareTo(courses.getCourses_name());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Courses)) {
			return false;
		}

		Courses courses = (Courses)object;

		long primaryKey = courses.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Courses> toCacheModel() {
		CoursesCacheModel coursesCacheModel = new CoursesCacheModel();

		coursesCacheModel.uuid = getUuid();

		String uuid = coursesCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			coursesCacheModel.uuid = null;
		}

		coursesCacheModel.coursesId = getCoursesId();

		coursesCacheModel.groupId = getGroupId();

		coursesCacheModel.companyId = getCompanyId();

		coursesCacheModel.userId = getUserId();

		coursesCacheModel.userName = getUserName();

		String userName = coursesCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			coursesCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			coursesCacheModel.createDate = createDate.getTime();
		}
		else {
			coursesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			coursesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			coursesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		coursesCacheModel.Courses_img = getCourses_img();

		String Courses_img = coursesCacheModel.Courses_img;

		if ((Courses_img != null) && (Courses_img.length() == 0)) {
			coursesCacheModel.Courses_img = null;
		}

		coursesCacheModel.Courses_name = getCourses_name();

		String Courses_name = coursesCacheModel.Courses_name;

		if ((Courses_name != null) && (Courses_name.length() == 0)) {
			coursesCacheModel.Courses_name = null;
		}

		coursesCacheModel.Courses_des = getCourses_des();

		String Courses_des = coursesCacheModel.Courses_des;

		if ((Courses_des != null) && (Courses_des.length() == 0)) {
			coursesCacheModel.Courses_des = null;
		}

		coursesCacheModel.Courses_type = getCourses_type();

		String Courses_type = coursesCacheModel.Courses_type;

		if ((Courses_type != null) && (Courses_type.length() == 0)) {
			coursesCacheModel.Courses_type = null;
		}

		coursesCacheModel.Courses_rating = getCourses_rating();

		String Courses_rating = coursesCacheModel.Courses_rating;

		if ((Courses_rating != null) && (Courses_rating.length() == 0)) {
			coursesCacheModel.Courses_rating = null;
		}

		return coursesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Courses, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Courses, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Courses, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Courses)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Courses>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Courses.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _coursesId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _Courses_img;
	private String _Courses_name;
	private String _Courses_des;
	private String _Courses_type;
	private String _Courses_rating;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Courses, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Courses)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("coursesId", _coursesId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("Courses_img", _Courses_img);
		_columnOriginalValues.put("Courses_name", _Courses_name);
		_columnOriginalValues.put("Courses_des", _Courses_des);
		_columnOriginalValues.put("Courses_type", _Courses_type);
		_columnOriginalValues.put("Courses_rating", _Courses_rating);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("coursesId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("Courses_img", 256L);

		columnBitmasks.put("Courses_name", 512L);

		columnBitmasks.put("Courses_des", 1024L);

		columnBitmasks.put("Courses_type", 2048L);

		columnBitmasks.put("Courses_rating", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Courses _escapedModel;

}