/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fironlineser.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FIRRR service. Represents a row in the &quot;FIRFOO_FIRRR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>fironlineser.model.impl.FIRRRModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>fironlineser.model.impl.FIRRRImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FIRRR
 * @generated
 */
@ProviderType
public interface FIRRRModel extends BaseModel<FIRRR> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a firrr model instance should use the {@link FIRRR} interface instead.
	 */

	/**
	 * Returns the primary key of this firrr.
	 *
	 * @return the primary key of this firrr
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this firrr.
	 *
	 * @param primaryKey the primary key of this firrr
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this firrr.
	 *
	 * @return the uuid of this firrr
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this firrr.
	 *
	 * @param uuid the uuid of this firrr
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the fir ID of this firrr.
	 *
	 * @return the fir ID of this firrr
	 */
	public long getFirId();

	/**
	 * Sets the fir ID of this firrr.
	 *
	 * @param firId the fir ID of this firrr
	 */
	public void setFirId(long firId);

	/**
	 * Returns the complainant name of this firrr.
	 *
	 * @return the complainant name of this firrr
	 */
	@AutoEscape
	public String getComplainantName();

	/**
	 * Sets the complainant name of this firrr.
	 *
	 * @param complainantName the complainant name of this firrr
	 */
	public void setComplainantName(String complainantName);

	/**
	 * Returns the incident date of this firrr.
	 *
	 * @return the incident date of this firrr
	 */
	public Date getIncidentDate();

	/**
	 * Sets the incident date of this firrr.
	 *
	 * @param incidentDate the incident date of this firrr
	 */
	public void setIncidentDate(Date incidentDate);

	/**
	 * Returns the incident details of this firrr.
	 *
	 * @return the incident details of this firrr
	 */
	@AutoEscape
	public String getIncidentDetails();

	/**
	 * Sets the incident details of this firrr.
	 *
	 * @param incidentDetails the incident details of this firrr
	 */
	public void setIncidentDetails(String incidentDetails);

	/**
	 * Returns the status of this firrr.
	 *
	 * @return the status of this firrr
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this firrr.
	 *
	 * @param status the status of this firrr
	 */
	public void setStatus(String status);

	/**
	 * Returns the timeline of this firrr.
	 *
	 * @return the timeline of this firrr
	 */
	@AutoEscape
	public String getTimeline();

	/**
	 * Sets the timeline of this firrr.
	 *
	 * @param timeline the timeline of this firrr
	 */
	public void setTimeline(String timeline);

	/**
	 * Returns the modification details of this firrr.
	 *
	 * @return the modification details of this firrr
	 */
	@AutoEscape
	public String getModificationDetails();

	/**
	 * Sets the modification details of this firrr.
	 *
	 * @param modificationDetails the modification details of this firrr
	 */
	public void setModificationDetails(String modificationDetails);

	/**
	 * Returns the user ID of this firrr.
	 *
	 * @return the user ID of this firrr
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this firrr.
	 *
	 * @param userId the user ID of this firrr
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this firrr.
	 *
	 * @return the user uuid of this firrr
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this firrr.
	 *
	 * @param userUuid the user uuid of this firrr
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this firrr.
	 *
	 * @return the create date of this firrr
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this firrr.
	 *
	 * @param createDate the create date of this firrr
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this firrr.
	 *
	 * @return the modified date of this firrr
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this firrr.
	 *
	 * @param modifiedDate the modified date of this firrr
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public FIRRR cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}