/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fironlineser.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.Phone;

import java.util.List;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SignupUser service. Represents a row in the &quot;FIRFOO_SignupUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>fironlineser.model.impl.SignupUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>fironlineser.model.impl.SignupUserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SignupUser
 * @generated
 */
@ProviderType
public interface SignupUserModel extends BaseModel<SignupUser> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a signup user model instance should use the {@link SignupUser} interface instead.
	 */

	/**
	 * Returns the primary key of this signup user.
	 *
	 * @return the primary key of this signup user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this signup user.
	 *
	 * @param primaryKey the primary key of this signup user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this signup user.
	 *
	 * @return the uuid of this signup user
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this signup user.
	 *
	 * @param uuid the uuid of this signup user
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the signup user ID of this signup user.
	 *
	 * @return the signup user ID of this signup user
	 */
	public long getSignupUserId();

	/**
	 * Sets the signup user ID of this signup user.
	 *
	 * @param signupUserId the signup user ID of this signup user
	 */
	public void setSignupUserId(long signupUserId);

	/**
	 * Returns the signup user uuid of this signup user.
	 *
	 * @return the signup user uuid of this signup user
	 */
	public String getSignupUserUuid();

	/**
	 * Sets the signup user uuid of this signup user.
	 *
	 * @param signupUserUuid the signup user uuid of this signup user
	 */
	public void setSignupUserUuid(String signupUserUuid);

	/**
	 * Returns the login name of this signup user.
	 *
	 * @return the login name of this signup user
	 */
	@AutoEscape
	public String getLoginName();

	/**
	 * Sets the login name of this signup user.
	 *
	 * @param loginName the login name of this signup user
	 */
	public void setLoginName(String loginName);

	/**
	 * Returns the first name of this signup user.
	 *
	 * @return the first name of this signup user
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this signup user.
	 *
	 * @param firstName the first name of this signup user
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this signup user.
	 *
	 * @return the last name of this signup user
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this signup user.
	 *
	 * @param lastName the last name of this signup user
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email of this signup user.
	 *
	 * @return the email of this signup user
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this signup user.
	 *
	 * @param email the email of this signup user
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone no of this signup user.
	 *
	 * @return the phone no of this signup user
	 */
	@AutoEscape
	public String getPhoneNo();

	/**
	 * Sets the phone no of this signup user.
	 *
	 * @param phone the phone no of this signup user
	 */
	public void setPhoneNo(String phone);

	/**
	 * Returns the password_ of this signup user.
	 *
	 * @return the password_ of this signup user
	 */
	@AutoEscape
	public String getPassword_();

	/**
	 * Sets the password_ of this signup user.
	 *
	 * @param password_ the password_ of this signup user
	 */
	public void setPassword_(String password_);

	/**
	 * Returns the role of this signup user.
	 *
	 * @return the role of this signup user
	 */
	@AutoEscape
	public String getRole();

	/**
	 * Sets the role of this signup user.
	 *
	 * @param role the role of this signup user
	 */
	public void setRole(String role);

	/**
	 * Returns the active of this signup user.
	 *
	 * @return the active of this signup user
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this signup user is active.
	 *
	 * @return <code>true</code> if this signup user is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this signup user is active.
	 *
	 * @param active the active of this signup user
	 */
	public void setActive(boolean active);

	/**
	 * Returns the activation token of this signup user.
	 *
	 * @return the activation token of this signup user
	 */
	@AutoEscape
	public String getActivationToken();

	/**
	 * Sets the activation token of this signup user.
	 *
	 * @param activationToken the activation token of this signup user
	 */
	public void setActivationToken(String activationToken);

	@Override
	public SignupUser cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}