/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fironlineser.model.impl;

import fironlineser.model.FIRRR;

import fironlineser.service.FIRRRLocalServiceUtil;

/**
 * The extended model base implementation for the FIRRR service. Represents a row in the &quot;FIRFOO_FIRRR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FIRRRImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FIRRRImpl
 * @see FIRRR
 * @generated
 */
public abstract class FIRRRBaseImpl extends FIRRRModelImpl implements FIRRR {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a firrr model instance should use the <code>FIRRR</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FIRRRLocalServiceUtil.addFIRRR(this);
		}
		else {
			FIRRRLocalServiceUtil.updateFIRRR(this);
		}
	}

}