/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fironlineser.model.impl;

import fironlineser.model.SignupUser;

import fironlineser.service.SignupUserLocalServiceUtil;

/**
 * The extended model base implementation for the SignupUser service. Represents a row in the &quot;FIRFOO_SignupUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SignupUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SignupUserImpl
 * @see SignupUser
 * @generated
 */
public abstract class SignupUserBaseImpl
	extends SignupUserModelImpl implements SignupUser {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a signup user model instance should use the <code>SignupUser</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SignupUserLocalServiceUtil.addSignupUser(this);
		}
		else {
			SignupUserLocalServiceUtil.updateSignupUser(this);
		}
	}

}